version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run: echo $ENCODED_KEYSTORE | base64 --decode >> ${HOME}/repo/keystore.jks
      - run: echo 'export KEYSTORE_FILE=${HOME}/repo/keystore.jks' >> $BASH_ENV
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/
